# Baseline Linear Regression

### What the baseline setup should contain

1. Objective
2. Define X and y
3. Train/Test Split
4. Separate feature types
5. Preprocessing
6. Baseline Linear Regression
7. Evaluate on validation/test data
8. Record baseline results
9. Baseline interpretation

## 1. Objective

The objective of this notebook is to establish a baseline performance
for predicting `median_house_value` using Linear Regression.

This baseline will provide a reference point for subsequent experiments
investigating training data size, number of features, feature selection,
geographic information, feature scaling, model complexity, regularization,
and outlier sensitivity.

The baseline should use a relatively simple and reproducible modeling
pipeline so that changes in performance can be attributed to subsequent
experimental modifications.

In [46]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [47]:
df = pd.read_csv("../Data/Raw/housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

### 2. Define X and y

In [48]:
X = df.drop(columns=["median_house_value"])

In [49]:
y =df['median_house_value']

In [50]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

### 3. Train Test Split the Data

In [51]:
from sklearn.model_selection import train_test_split

X_train,y_train, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

### 4. Seprate Numerical Features and Categorical Feature

In [52]:
numerical_features = X_train.select_dtypes(include=('int64', 'float64')).columns

categorical_features = X_train.select_dtypes(include=('str','object')).columns

### 5. Preprocessing
Build the preprocessing pipeline

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

df["total_bedrooms"] = df["total_bedrooms"].fillna(
    df["total_bedrooms"].median())

#Numerical Pipeline
numerical_pipeline = Pipeline([
    ('scalar',StandardScaler())
])

#Categorical Pipeline
categorical_pipeline = Pipeline([
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])

#Applying the Transformation 
preprocessor = ColumnTransformer([
    ('num', numerical_pipeline, numerical_features),
    ('Cat', categorical_pipeline, categorical_features)
])

In [59]:
print("Numerical features:")
print(numerical_features)

Numerical features:
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='str')

### 6. Train the baseline Linear Regression

In [60]:
from sklearn.linear_model import LinearRegression

baseline_lr = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

In [61]:
#Training the Model
baseline_lr.fit(X_train, y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values